# Generated by Django 2.0.3 on 2018-06-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user_id',
        ),
    ]
